
namespace OpenCover.Framework.Strategy
{
    using System.Linq;
    using System.Runtime.CompilerServices;

    using Mono.Cecil;

    public class LambdaAutogeneratedBranch : ISkippedBranch
    {
        public bool IsSkipped(InstructionData instructionData)
        {
            if (instructionData == null 
                || instructionData.Instruction == null
                || instructionData.Instruction.Previous == null
                || !(instructionData.Instruction.Previous.Operand is FieldDefinition)) return false;
            var instruction = instructionData.Instruction;
            var operand = instruction.Previous.Operand as FieldDefinition;
            return operand.CustomAttributes.Any(x => x.AttributeType.FullName == typeof(CompilerGeneratedAttribute).FullName);
        }
    }
}
