
namespace OpenCover.Framework.Strategy
{
    using System.Linq;
    using System.Runtime.CompilerServices;

    using Mono.Cecil;
    using Mono.Cecil.Cil;

    public class LambdaAutogeneratedBranch : ISkippedBranch
    {
        public bool IsSkipped(Instruction instruction)
        {
            if (instruction == null || instruction.Previous == null || !(instruction.Previous.Operand is FieldDefinition)) return false;
            var operand = instruction.Previous.Operand as FieldDefinition;
            return operand.CustomAttributes.Any(x => x.AttributeType.FullName == typeof(CompilerGeneratedAttribute).FullName);
        }
    }
}
